name : lint

on:
  pull_request:
      branches: 
        - main


jobs:
  eslint:
    name: run eslint
    runs-on: ubuntu-latest

    steps: 
      - name : checkout branches
        run: actions/checkout@v3

      - name: Set up
        run: actions/setup-node@v3

      - name : installation 
        run: npm installation

      - name: run eslint
        run: npm run lint